print("Hello World!!")

# Python Crash Course


In [4]:
print(1+1)

2


In [1]:
# Message for world 
print("Hello World!!")


Hello World!!


In [4]:
num = 12
name = krishna


NameError: name 'krishna' is not defined

In [5]:
'My name is: {} and my age is {}'.format(num,name)


NameError: name 'name' is not defined

In [8]:
'My name is: {} and my age is {}'.format(num,name)

'My name is: 12 and my age is krishna'

In [7]:
num = 12
name = 'krishna'

In [9]:
'My name is: {} and my age is {}'.format(num,name)

'My name is: 12 and my age is krishna'

In [13]:
print(My name is: {} and my age is {}'.format(num,name))

SyntaxError: invalid syntax (<ipython-input-13-3791e7a9913f>, line 1)

In [15]:
print('My name is: {} and my age is {}'.format(num,name)

SyntaxError: unexpected EOF while parsing (<ipython-input-15-467bc3fc497e>, line 1)

In [17]:
print('My name is: {} and my age is {}'.format(num,name))

My name is: 12 and my age is krishna


In [20]:
print('My name is: {one} and my age is {two},write(one)'.format(one=num,two=name))

My name is: 12 and my age is krishna,write(one)


In [21]:
s = 'Hello'

In [23]:
s[4]

'o'

In [24]:
s[:3]

'Hel'

In [25]:
s[0:]

'Hello'

In [26]:
s[1:]

'ello'

In [27]:
s='abcdefghijk'

In [28]:
s[3:6]

'def'

In [29]:
s[3]

'd'

In [30]:
[1,2,3]

[1, 2, 3]

In [31]:
my_list = ['a','b','c']

In [32]:
my_list.append('d')

In [33]:
my_list


['a', 'b', 'c', 'd']

In [34]:
my_list[0]

'a'

In [36]:
my_list[1:4]

['b', 'c', 'd']

In [37]:
my_list=z

NameError: name 'z' is not defined

In [41]:
my_list[0]='z'


In [42]:
my_list

['z', 'b', 'c', 'd']

In [44]:
nest=[1,2,[3,4]]

In [46]:
nest[0]

1

In [47]:
nest[2][0]

3

In [48]:
nest[2][1]

4

In [49]:
nest = [1,2,3,[4,5],['target']]

In [51]:
nest[4][0]

'target'

In [52]:
nest = [1,2,3,[4,5,['target']]]

In [55]:
nest[3][2]

['target']

In [56]:
nest[3][2][0]

'target'

In [57]:
d = {'key1':'ashish','key2':'123'}

In [59]:
d['key1']

'ashish'

In [60]:
d['key2']

'123'

In [61]:
d = {'key1':[1,2,3]}

In [63]:
d['key1'][2]

3

In [64]:
d['key1'][1]

2

In [65]:
d={'k1':{'innerkey':[1,2,3]}}

In [66]:
d['k1']

{'innerkey': [1, 2, 3]}

In [67]:
d['k1']['innerkey'][1]

2

In [68]:
True

True

In [69]:
False

False

In [70]:
my_list=[1,2,3]

In [71]:
my_list[0]

1

In [72]:
t =[1,2,3]

In [73]:
t[2]

3

In [74]:
t[0]

1

In [75]:
#Tuple uses the () instead of []
t=(1,2,3)

In [76]:
t

(1, 2, 3)

In [77]:
t(0)

TypeError: 'tuple' object is not callable

In [79]:
t[0]

1

In [80]:
t[1]

2

In [81]:
t[2]

3

In [82]:
t[0]='new'

TypeError: 'tuple' object does not support item assignment

In [83]:
t


(1, 2, 3)

In [84]:
{1,2,3}


{1, 2, 3}

In [86]:
{1,1,2,2,3,3,4,5,66,7,8,9,0}

{0, 1, 2, 3, 4, 5, 7, 8, 9, 66}

In [89]:
set([1,1,2,2,3,3,4,5,6,7,8,9,0,9,8,7,6,5,0])

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [90]:
s={1,2,3,4}

In [91]:
s.add(5)

In [92]:
s


{1, 2, 3, 4, 5}

In [93]:
1>2

False

In [94]:
1<2

True

In [95]:
1 == 1

True

In [96]:
1 == 5

False

In [97]:
1 = 1

SyntaxError: can't assign to literal (<ipython-input-97-ecdac3dcabfd>, line 1)

In [98]:
'hi' == 'hi'

True

In [99]:
'hi' == 'Hi'

False

In [100]:
1 <2  and 2< 3

True

In [102]:
1 <2  or  2>3

True

In [104]:
True and  False

False

In [105]:
if 1 <2:
    print('yep!')

yep!


In [106]:
if True:
    print('Perform Code')

Perform Code


In [107]:
if True:
    x= 2+2

In [108]:
x


4

In [109]:
if 1 ==1:
    print('that true')

that true


In [110]:
if 1 ==2:
    print('that true')

In [111]:
if 1 ==2:
    print('that true')
    else:
        print('Not so funny')

SyntaxError: invalid syntax (<ipython-input-111-b6b1cba3422c>, line 3)

In [119]:
if 1 == 2:
    print('that true')
elif 3==3 : 
    print('Middle')
else:
    print('Not so funny')

Middle


In [121]:
if 1 == 2:
    print('that true')
elif 3== 4: 
    print('Middle')
elif 4==4 :
    print('Below Middle')
else:
    print('Not so funny')

Below Middle


In [1]:
d = {'key1':'value1','key2':'value2'}

In [4]:
d['key1']

'value1'

In [9]:
d={'key1':'[1,2,3]'}

In [7]:
d


{'key1': '123'}

In [8]:
d['key1']

'123'

In [10]:
d

{'key1': '[1,2,3]'}

In [11]:
d['key1'][2]

','

In [17]:
d={'my_list':[1,2,3]}

In [18]:
d['my_list']

[1, 2, 3]

In [20]:
d['my_list'][0]

1

In [21]:
d={'k1':{'inner_key':[1,2,3]}}

In [23]:
d['k1']['inner_key'][1]

2

In [24]:
#Tuple immutable 

In [29]:
T=[1,2,3]

In [26]:
t[0]

1

In [27]:
t=(1,2,3)

In [30]:
T[0]='New'

In [31]:
T

['New', 2, 3]

In [32]:
t(0)

TypeError: 'tuple' object is not callable

In [33]:
t[0]

1

In [34]:
t[0]='NEW'

TypeError: 'tuple' object does not support item assignment

In [36]:
S={1,1,1,1,2,2,2,23,3,4,5,6}

In [37]:
S

{1, 2, 3, 4, 5, 6, 23}

In [43]:
S.add(7)

In [44]:
S

{1, 2, 3, 4, 5, 6, 7, 23}

In [45]:
1 > 2

False

In [46]:
1 < 2

True

In [47]:
1 !=1

False

In [48]:
1 == 1

True

In [49]:
1 != 2

True

In [51]:
'HI' == '2HI'

False

In [52]:
seq= [1,2,3,4,5,6,7,8,9,0]
for item in seq
print(item)

SyntaxError: invalid syntax (<ipython-input-52-13f760614d5f>, line 2)

In [53]:
seq= [1,2,3,4,5,6,7,8,9,0]


In [54]:
seq


[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [56]:
for item in seq:
     print(item)

1
2
3
4
5
6
7
8
9
0


In [58]:
for num in seq:
    print('Hello World!')

Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!
Hello World!


In [59]:
i = 1
while i < 10:
    print('i is: {}'.format(i))
    i=i+1

i is: 1
i is: 2
i is: 3
i is: 4
i is: 5
i is: 6
i is: 7
i is: 8
i is: 9


In [60]:
for x in range(0,10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [61]:
list (range(0,5))

[0, 1, 2, 3, 4]

In [63]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [64]:
range=1

In [65]:
range


1

In [66]:
x = [1,2,3,4,5,6,7,8,9]

In [69]:
out = []

In [71]:
for num in x:
    out.append(num**2)

In [72]:
out


[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [73]:
#Important 
for num in x:
    out.append(num)

In [74]:
out

[1, 4, 9, 16, 25, 36, 49, 64, 81, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [75]:
print(out)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [79]:
#Important 
out = [num**3 for num in x]

In [77]:
out

[1, 8, 27, 64, 125, 216, 343, 512, 729]

In [78]:
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [80]:
def my_fux(name):
    print('Hello' + Name)

In [82]:
my_fux('Sania')

NameError: name 'Name' is not defined

In [3]:
out = [num**2 for num in x]

TypeError: 'int' object is not iterable

In [2]:
x=2

In [4]:
out

NameError: name 'out' is not defined

In [6]:
y = 9

In [7]:
abc = [num**3 for num in y]

TypeError: 'int' object is not iterable

In [9]:
 y = [1,3,6,9]   

In [10]:
abc = [num**3 for num in y]

In [11]:
abc


[1, 27, 216, 729]

In [12]:
def my_func(param1):
    print(param1)

In [13]:
my_func('hello')

hello


In [14]:
def mx_fx(sing):
    print(sing)

In [16]:
mx_fx('Kratos')

Kratos


In [21]:
def greet(name):
    print('Hello ' + name)

In [22]:
greet('Tap')

Hello Tap


In [23]:
greet(Elon)

NameError: name 'Elon' is not defined

In [24]:
greet('Elon')

Hello Elon


In [25]:
greet('Iron Man')

Hello Iron Man


In [26]:
def mx_fx(name='Default Name'):
    print('Hello ' + name)

In [28]:
mx_fx('Kiara')

Hello Kiara


In [29]:
mx_fx()

Hello Default Name


In [30]:
mx_fx

<function __main__.mx_fx(name='Default Name')>

In [32]:
def square(num):
    print(num**2)

In [33]:
square(2)

4


In [37]:
def square(num):
 """ this is function 
 to square the subjected value """
    return num**2

IndentationError: unexpected indent (<ipython-input-37-5e9753c66595>, line 4)

In [38]:
def square(num):
 """ this is function 
 to square the subjected value """
    return num**2

IndentationError: unexpected indent (<ipython-input-38-5e9753c66595>, line 4)

In [49]:
def square(num):
    """ this is test square function"""
    return num**2

In [43]:
square(6565)

43099225

In [57]:
def time2(var):
    return var*2

In [58]:
def time2(var):return var*2

In [56]:
time2(9)

18

In [50]:
#Map function#

In [51]:
seq = [1,2,3,4,5]

In [52]:
map(time2(seq))

TypeError: map() must have at least two arguments.

In [53]:
map(time2,seq)

In [54]:
list(map(time2,seq))

[2, 4, 6, 8, 10]

In [60]:
t= lambda var:var**2

In [61]:
 t(97)

9409

In [63]:
map(lambda var:var*3,seq)

In [64]:
list(map(lambda var:var*3,seq))

[3, 6, 9, 12, 15]

In [65]:
z= lambda num:num**3

In [66]:
z(545)

161878625

In [67]:
seq = [2,4,6,8,10]

In [68]:
map(lambda num:num**2,seq)

In [71]:
list(filter(lambda num:num**2,seq))

[2, 4, 6, 8, 10]

In [72]:
list(filter(lambda num:num%2 ==0,seq))

[2, 4, 6, 8, 10]

In [73]:
s = 'Hello bid Iron Man Here !!'

In [75]:
s.capitalize()

'Hello bid iron man here !!'

In [77]:
s.upper()

'HELLO BID IRON MAN HERE !!'

In [78]:
s.split()

['Hello', 'bid', 'Iron', 'Man', 'Here', '!!']

In [80]:
s.split('o')

['Hell', ' bid Ir', 'n Man Here !!']

In [81]:
lst = [1,2,3,4,5,6,7,8,9,10]

In [82]:
lst.pop


<function list.pop(index=-1, /)>

In [83]:
item = lst.pop()

In [84]:
itme

NameError: name 'itme' is not defined

In [85]:
item

10

In [86]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [1]:
s = 'Hello Guys how are you doing today !!'
        

In [2]:
s.upper()

'HELLO GUYS HOW ARE YOU DOING TODAY !!'

In [3]:
s.split()

['Hello', 'Guys', 'how', 'are', 'you', 'doing', 'today', '!!']

In [4]:
tweet = 'Go Sleep Well !!'

In [5]:
tweet.split()

['Go', 'Sleep', 'Well', '!!']

In [7]:
tweet.split('o')

['G', ' Sleep Well !!']

In [8]:
d ={'k1':1,'k2':2} 

In [9]:
d.keys()

dict_keys(['k1', 'k2'])

In [10]:
d.values()

dict_values([1, 2])

In [11]:
9lst=[1,2,3,4,5]

In [12]:
lst.pop()

5

In [13]:
lst

[1, 2, 3, 4]

In [14]:
lst =[1,2,3,4,5]

In [15]:
item= lst.pop()

In [16]:
item

5

In [17]:
first =lst.pop(0)

In [18]:
ew

1

In [19]:
first()

TypeError: 'int' object is not callable

In [20]:
lst.append('New')

In [21]:
lst

[2, 3, 4, 'New']

In [22]:
lst


[2, 3, 4, 'New']

In [23]:
x =[(1,2),(3,4),(5,6)]

In [24]:
x[0]

(1, 2)

In [27]:
x[0][1]

2

In [28]:
for item in x: print(item)

(1, 2)
(3, 4)
(5, 6)


In [29]:
for num in x: print(num)

(1, 2)
(3, 4)
(5, 6)


In [30]:
#Python crash course exercises#

In [31]:
7**4

2401

In [32]:
s = "Hi there Sam!"

In [33]:
s.split()

['Hi', 'there', 'Sam!']

In [3]:
print('The diameter of {} is {} kilometers.'format(Earth,12742))

SyntaxError: invalid syntax (<ipython-input-3-f16ea964dd1a>, line 1)

In [2]:
planet = "Earth"
diameter = 12742

In [6]:
print('The diameter of {} is {} kilometers'.format(planet,diameter))

The diameter of Earth is 12742 kilometers


In [3]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

In [15]:
lst[3][1][2][0]

'hello'

In [16]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [26]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [27]:
domainGet('user@domain.com')

NameError: name 'domainGet' is not defined

In [30]:
l='user@domain.com'

In [31]:
l.split()

['user@domain.com']

In [34]:
l.split('@')[1]

'domain.com'

In [42]:
def domainGet(email):
    return email.split('@')[1] 

In [43]:
email='dipeshkumar619@gmail.com'

NameError: name 'dipeshkumar619' is not defined

In [47]:
domainGet('dipeshkumar619@gmail.com')

'gmail.com'

In [48]:
def domainGet(email):
    return email.split('@')[1] 

In [49]:
domainGet('john@kk.com')

'kk.com'

In [52]:
def domainGet(email):
    return email.split('@')[1]

In [53]:
domainGet('apj@isro.com')

'isro.com'

In [54]:
def enduser(email):
    return email.split('@')[0]

In [56]:
enduser('apj@isro.com')

'apj'

In [57]:
string='Is there a dog here?'

In [60]:
string.find('x')

-1

In [94]:
def findstrg(string)
    string1 =string.lower()
    Z=string1.find('dog')
    if Z == -1:
        print(False)
    else:
        print(True)

SyntaxError: invalid syntax (<ipython-input-94-5c7879da58a0>, line 1)

In [82]:
findstring('Is there a dog  ?')

True


In [89]:
string='Is there a Dog  ?'

In [87]:
string1=string.lower()

In [90]:
string1

'is there a dog  ?'

In [99]:
def findDog(s):
    return 'dog' in s.lower().split()

In [100]:
findDog('i love dog and his name is symbian')

True

In [101]:
s = 'i love dog and his name is symbian'

In [105]:
s.lower().split()

['i', 'love', 'dog', 'and', 'his', 'name', 'is', 'symbian']

In [106]:
'dog' in s.lower().split()

True

In [113]:
def countDog(str):
    count=0
    for word in str.lower().split():
        if word == 'dog':
            count= count+1
    return count

In [115]:
countDog('dog DOG dog dog Dog dOg doG')

7

In [117]:
def countdog(str):
    count=0
    for word in str.lower().split():
        if word =='dog':
            count+=1
    return count

In [118]:
countdog('dog DOG dog dog Dog dOg doG')

7

In [119]:
countdog('This dog runs faster than the other dog dude!')

2

In [120]:
seq = ['soup','dog','salad','cat','great']

In [122]:
list(filter(lambda word: word[0]=='s',seq ))

['soup', 'salad']

In [142]:
def caught_speeding(speeding,is_birthday):

if is_birthday:
    speed = speeding -5
else:
    speed =speeding
    
if speed > 80:
    return 'Big Ticket'
elif speed 60:
    return 'Small Ticket
else:
    return 'No Ticket'
    
    
 

IndentationError: expected an indented block (<ipython-input-142-c81cacbecc11>, line 3)

 # Numpy Arrays

In [144]:
#the conda install is the recommended method if you have the anaconda distribution#
#conda install numpy
# pip install numpy

In [145]:
my_list = [1,2,3]

In [146]:
import numpy as np

In [147]:
arr= np.array(my_list)

In [148]:
arr

array([1, 2, 3])

In [149]:
my_mat = [(1,2,3),(4,5,6),(7,8,9)]

In [150]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [151]:
np.arange(0,11) #to count from one to next digit

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [152]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [153]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [154]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [155]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [156]:
np.ones(3)

array([1., 1., 1.])

In [164]:
np.ones((3,4)) # the np.ones(rows,columns)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [165]:
np.linspace(1,7,100) # to start the 1 dimensional starting from 1 to 7 with spaces of 100.

array([1.        , 1.06060606, 1.12121212, 1.18181818, 1.24242424,
       1.3030303 , 1.36363636, 1.42424242, 1.48484848, 1.54545455,
       1.60606061, 1.66666667, 1.72727273, 1.78787879, 1.84848485,
       1.90909091, 1.96969697, 2.03030303, 2.09090909, 2.15151515,
       2.21212121, 2.27272727, 2.33333333, 2.39393939, 2.45454545,
       2.51515152, 2.57575758, 2.63636364, 2.6969697 , 2.75757576,
       2.81818182, 2.87878788, 2.93939394, 3.        , 3.06060606,
       3.12121212, 3.18181818, 3.24242424, 3.3030303 , 3.36363636,
       3.42424242, 3.48484848, 3.54545455, 3.60606061, 3.66666667,
       3.72727273, 3.78787879, 3.84848485, 3.90909091, 3.96969697,
       4.03030303, 4.09090909, 4.15151515, 4.21212121, 4.27272727,
       4.33333333, 4.39393939, 4.45454545, 4.51515152, 4.57575758,
       4.63636364, 4.6969697 , 4.75757576, 4.81818182, 4.87878788,
       4.93939394, 5.        , 5.06060606, 5.12121212, 5.18181818,
       5.24242424, 5.3030303 , 5.36363636, 5.42424242, 5.48484

In [163]:
np.eye(10) #to create identity matrix 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [166]:
np.random.rand(5) # create 1 Dimensional matrix with 5 radom variables ..you will get values from 0 to 1

array([0.9038558 , 0.05165541, 0.33851559, 0.71272498, 0.5898331 ])

In [168]:
np.random.randn(5,3) # Create 2D matrix with 5 rows and 3 cols ....

array([[-0.49884439, -2.62874279,  0.05327618],
       [-1.42763321,  0.04678563, -0.4118403 ],
       [ 0.74406562, -2.40539546,  1.65149978],
       [-0.89699459, -0.23140446,  0.87842974],
       [-0.07321688, -1.20980291, -0.30800867]])

In [181]:
np.random.randint(0,100,11)

array([46, 20,  3, 94, 36, 60, 53, 73, 57, 34, 95])

In [189]:
arr=np.arange(50)

In [183]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [184]:
ranarr=np.random.randint(0,99,33)

In [185]:
ranarr

array([67, 92, 25, 66, 12, 30, 59, 70, 67, 62, 26, 47, 87, 57, 72, 20, 27,
       91, 18, 48,  1, 67,  8, 18,  5, 86, 40, 61, 19,  4, 43, 13, 88])

In [195]:
single=arr.reshape(5,10)

In [191]:
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [194]:
ranarr.max()

92

In [196]:
single.max()

49

In [198]:
single.min()

0

In [199]:
single

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [200]:
single.argmax() #to know the location of maximum value. 

49

In [202]:
single.argmin() #to knwo the minimum value location.

0

In [203]:
ranarr.max()

92

In [204]:
ranarr.argmax()

1

In [205]:
ranarr.argmin()

20

In [210]:
single.shape()

TypeError: 'tuple' object is not callable

In [211]:
single

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [214]:
single.shape # to knwo the shape and size of the matrix



(5, 10)

# Numpy Array Indexing


In [215]:
import numpy as np


In [231]:
arr = np.arange(0,11)

In [217]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [218]:
arr[4]

4

In [219]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [220]:
arr[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [221]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [222]:
arr[7:]

array([ 7,  8,  9, 10])

In [227]:
slice_arr=arr[:8]

In [229]:
slice_arr[:]=100

In [230]:
slice_arr

array([100, 100, 100, 100, 100, 100, 100, 100])

In [232]:
arr_copy=arr.copy()

In [233]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [236]:
arr_2d= np.array([[5,10,15],[20,25,30],[35,40,45]])

In [237]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [244]:
 arr_2d[2][2]

45

In [245]:
    arr_2d[1][2]

30